export const routes = {
  login: "/login",
  guestQr: "/qr/:qrToken",
  dashboard: "/",
  floor: "/floor",
  waiter: "/waiter",
  kitchen: "/kitchen",
  bar: "/bar",
  reports: "/reports",
  reservations: "/reservations",
  warehouse: "/warehouse",
  admin: "/admin",
  adminMenu: "/admin/menu",
  adminUsers: "/admin/users",
} as const;
